### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by zoral566** [mgrom/domoticz-AirHumidifier#1]
./MyHumidify.py 192.168.1.191 583476dbf6457cdf84aef497e6a167fd --debug
Traceback (most recent call last):
  File "./MyHumidify.py", line 59, in <module>
    print(MyHumidifier.status())
  File "/usr/local/lib/python3.5/dist-packages/miio/airhumidifier.py", line 254, in status
    properties
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 270, in send
    raise DeviceError(m.data.value["error"])
miio.exceptions.DeviceError: {'code': -9999, 'message': 'UART timeout'}

**Comment by mgrom** [comment]
Hmm... looks like a problem with miio library:
https://github.com/rytilahti/python-miio/issues/383

**Comment by Stimpy68** [comment]
I have the same problem, any way to fix this?
